GET http://localhost:9000/books/2
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:9000/books?where={
  "image": "image.png",
  "users": [
    {
      "name": "su",
      "age": 18
    },
    {
      "name": "su11",
      "age": 18
    }
  ]
 }
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:9000/books
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "image": "image.png",
  "users": [
    {
      "name": "su",
      "age": 18
    },
    {
      "name": "su11",
      "age": 18
    }
  ]
}

###

###
POST http://localhost:9000/books/multi
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

[
  {
    "users": [
      {
        "name": "su",
        "age": 18
      },
      {
        "name": "su11",
        "age": 18
      }
    ]
  },
  {
    "bookName": "起风了",
    "users": [
      {
        "name": "su",
        "age": 18
      },
      {
        "name": "su11",
        "age": 18
      }
    ]
  }
]

###
POST http://localhost:9000/books/test
Accept: */*
Cache-Control: no-cache
Content-Type: application/json



###

###
PUT http://localhost:9000/books
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "image": "image.png",
  "users": [
    {
      "name": "su",
      "age": 18
    },
    {
      "name": "su11",
      "age": 18
    }
  ]
}

###

DELETE http://localhost:9000/books?bookIds=%5b6%2c7%2c8%5d
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

DELETE  http://localhost:9000/books/18

###